### ISSUE TITLE
Raspberry Pi OSError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by thEpisode** [adafruit/Adafruit_CircuitPython_VEML6075#4]
Hi guys, I followed this tutorial https://learn.adafruit.com/adafruit-veml6075-uva-uvb-uv-index-sensor/python-circuitpython but when I'm trying to use the code I got the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 68, in __init__
    i2c.writeto(device_address, b'')
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 65, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 74, in __init__
    i2c.readfrom_into(device_address, result)
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 55, in readfrom_into
    return self._i2c.readfrom_into(address, buffer, stop=stop)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 44, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end-start)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 155, in read_bytes
    return self._device.read(number)
OSError: [Errno 121] Remote I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "veml6075.py", line 8, in <module>
    veml = adafruit_veml6075.VEML6075(i2c, integration_time=100)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_veml6075.py", line 106, in __init__
    self._i2c = I2CDevice(i2c_bus, _VEML6075_ADDR)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 76, in __init__
    raise ValueError("No I2C device at address: %x" % device_address)
ValueError: No I2C device at address: 10
```
Code used:
```
import time
import board
import busio
import adafruit_veml6075
 
i2c = busio.I2C(board.SCL, board.SDA)
 
veml = adafruit_veml6075.VEML6075(i2c, integration_time=100)
 
print("Integration time: %d ms" % veml.integration_time)
 
while True:
    print(veml.uv_index)
    time.sleep(1)
```

I checked the connections and enabled I2C from Raspi config.

Pd: Raspberry Pi 3 B+

**Comment by caternuson** [comment]
Can you run i2cdetect from the command line and post output here.
```
i2cdetect -y 1
```

**Comment by thEpisode** [comment]
Sure, the result is:

```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         

```

**Comment by caternuson** [comment]
It's not showing up at all. It may be hardware related. Have you posted this in the forums?
https://forums.adafruit.com/

**Comment by thEpisode** [comment]
Umm no, I haven't posted this yet, but what is the problem? what has to be seen in that result?

**Comment by caternuson** [comment]
The above is a scan of all devices attached to the I2C bus. It should return the address for any found device. In your case, it returned nothing. Most often this a wiring or solder issue. Posting a photo of your setup in the forums would help with figuring that out.

**Comment by thEpisode** [comment]
ooohh thanks, I'll be close this issue while my problem are solved, thank you!

**Comment by ShaunBorg** [comment]
Hello I have the same problem but mine is detecting the object

**Comment by caternuson** [comment]
@ShaunBorg Also worth posting in the forums.

**Comment by lpnaunau** [comment]
Hi, I'm having also this error and I'm detecting the device as well. I think there is an issue with the Adafruit library. @ShaunBorg did you find a solution ?

**Comment by ShaunBorg** [comment]
No i had 1 week to find and I didnt got a clue how to do it

**Comment by caternuson** [comment]
Please post these issue in [the forums](https://forums.adafruit.com). It's likely either hardware related or something specific to your RPi setup. Everything checks out with fresh install of Raspian Lite (2019-04-08), blinka install, and this library.

Set up:
![rpi_veml6075_test](https://user-images.githubusercontent.com/8755041/56597491-6fbb4b00-65a7-11e9-9e7d-6416ac60eace.jpg)

What running `i2cdetect` should look like:
```
pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: 10 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 
```
And running this test code ([from guide](https://learn.adafruit.com/adafruit-veml6075-uva-uvb-uv-index-sensor/python-circuitpython#full-example-code-6-15)):
```python
import time
import board
import busio
import adafruit_veml6075

i2c = busio.I2C(board.SCL, board.SDA)

veml = adafruit_veml6075.VEML6075(i2c, integration_time=100)

print("Integration time: %d ms" % veml.integration_time)

while True:
    print(veml.uv_index)
    time.sleep(1)
```
should look something like this:
```
pi@raspberrypi:~ $ python3 veml_test.py
Integration time: 400 ms
-0.023346945
0.0258415
0.027867500000000003
0.027137
0.027137
0.025841
```

**Comment by pouriya123** [comment]
Does anyone have an idea for this ?
______________________________________________________________________
i connected pca9685 to pi4 
and run:
#######################################################################
#""Simple test for a standard servo on channel 0 and a continuous rotation servo on channel 1."""
import time
from adafruit_servokit import ServoKit
# Set channels to the number of servo channels on your kit.
# 8 for FeatherWing, 16 for Shield/HAT/Bonnet.
kit = ServoKit(channels=8)
kit.servo[0].angle = 180
kit.continuous_servo[1].throttle = 1
time.sleep(1)
kit.continuous_servo[1].throttle = -1
time.sleep(1)
kit.servo[0].angle = 0
kit.continuous_servo[1].throttle = 0
########################################################################
but i receive :

Traceback (most recent call last):
  File "/home/pi/software/servo.py", line 7, in <module>
    kit = ServoKit(channels=8)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_servokit.py", line 92, in __init__
    self._pca.frequency = 50
  File "/usr/local/lib/python3.7/dist-packages/adafruit_pca9685.py", line 159, in frequency
    self.mode1_reg = (old_mode & 0x7F) | 0x10  # Mode 1, sleep
  File "/usr/local/lib/python3.7/dist-packages/adafruit_register/i2c_struct.py", line 95, in __set__
    i2c.write(buf)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_bus_device/i2c_device.py", line 104, in write
    self.i2c.writeto(self.device_address, buf, start=start, end=end, stop=stop)
  File "/usr/local/lib/python3.7/dist-packages/busio.py", line 110, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 49, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO/smbus.py", line 308, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error
###########################################################################
*----------->

 i2cdetect -y 1

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- 05 06 07 08 09 0a 0b 0c 0d 0e 0f 
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f 
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
70: 70 71 72 73 74 75 76 77

**Comment by OguzCiftci** [comment]
Did you try to add 1 second delay after the i2c connection is defined?

**Comment by AnastaZIuk** [comment]
> Hello I have the same problem but mine is detecting the object

and somebody got an answer what to do in that case?

**Comment by danchendrickson** [comment]
I get a the same error in my code.  My code will work, I will see the sensor at 0x68 or 0x69, and the code will run.  If I then stop the code to make a change (like how it outputs the data to file, unrelated to this section) the sensor gives Errno 121.  I2Cdetect then returns all 0s.

**Comment by Purvendra** [comment]
I am able to detect the device ID, still getting the same error. Can anyone help me out with this please?
