### ISSUE TITLE
RuntimeError: Incorrect VEML6075 ID 0x00

### ISSUE THREAD

**Issue by romgapuz** [adafruit/Adafruit_CircuitPython_VEML6075#6]
Need help. Whenever I ran the sample code from README.rst I get the following error:

> RuntimeError: Incorrect VEML6075 ID 0x00

When I run "i2cdetect -y 1" I see the device is detected at 10.

**Comment by dhalbert** [comment]
Which board are you using the VEML6075 breakout with, and are you using our VEML6075 breakout?

**Comment by romgapuz** [comment]
I’m using Raspberry Pi and Adafruit VEML6075 connected via i2c

**Comment by ladyada** [comment]
hmm i just pip installed it and it worked so unclear whats up 
please post in the adafruit forum maybe they can help you with wiring or replacement :)
